# Generated by Django 3.1.5 on 2021-01-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210113_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=140),
        ),
    ]
