# Generated by Django 3.1.5 on 2021-01-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210114_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
