# Generated by Django 3.1.5 on 2021-01-14 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_delete_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='who_im_following',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
